
---
language: php
php:
    - "5.6"
services:
    - docker
branches:
    only:
        - master

cache:
    directories:
    - composer_vendordir
env:
    global:
    - DEST_ID=nsent
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:${NSVER}
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e ENDPOINTS_PACK
        "


script: >
    echo "%github_token ${GITHUB_TOKEN}" >> $PWD/.rpmmacros
    && echo "%composer_vendordir /srv/makerpms/composer_vendordir" >> $PWD/.rpmmacros
    && mkdir -p composer_vendordir && chmod 1777 composer_vendordir
    && docker run -ti --name makerpms ${EVARS}
    --hostname b${TRAVIS_BUILD_NUMBER}.nethserver.org
    --volume $PWD:/srv/makerpms/src:ro
    --volume $PWD/.rpmmacros:/srv/makerpms/.rpmmacros
    --volume $PWD/composer_vendordir:/srv/makerpms/composer_vendordir
    ${DOCKER_IMAGE} makerpms-travis -s *.spec
    && docker commit makerpms nethserver/build
    && docker run -ti ${EVARS}
    -e SECRET
    -e SECRET_URL
    -e AUTOBUILD_SECRET
    -e AUTOBUILD_SECRET_URL
    nethserver/build uploadrpms-travis

